name: sagar regmi
on:
    push:
        branches: [ main ]
  
jobs:
    demo:
        runs-on: ubuntu-latest

           
        steps: 
         - name: Greetings
           run: echo "hello sagar i am from vm"
